### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by vhuber** [wkyoshe/stageM1#17]
Please tell me if your library is static or shared, and what is the difference between theses kind of library.

**Comment by wkyoshe** [comment]
# The library is a shared library.
- Shared libraries are .so (or in Windows .dll, or in OS X .dylib) files. All the code relating to the library is in this file, and it is referenced by programs using it at run-time. A program using a shared library only makes reference to the code that it uses in the shared library.  
- Static libraries are .a (or in Windows .lib) files. All the code relating to the library is in this file, and it is directly linked into the program at compile time. A program using a static library takes copies of the code that it uses from the static library and makes it part of the program. [Windows also has .lib files which are used to reference .dll files, but they act the same way as the first one].

### advantages and disadvantages in each method.
- Shared libraries reduce the amount of code that is duplicated in each program that makes use of the library, keeping the binaries small. It also allows you to replace the shared object with one that is functionally equivalent, but may have added performance benefits without needing to recompile the program that makes use of it. Shared libraries will, however have a small additional cost for the execution of the functions as well as a run-time loading cost as all the symbols in the library need to be connected to the things they use. Additionally, shared libraries can be loaded into an application at run-time, which is the general mechanism for implementing binary plug-in systems.  
- Static libraries increase the overall size of the binary, but it means that you don't need to carry along a copy of the library that is being used. As the code is connected at compile time there are not any additional run-time loading costs. The code is simply there.

**Comment by vhuber** [comment]
I have a static one.

``` sh
vhuber@wifi-irma13:~/stageM1% mkdir build
vhuber@wifi-irma13:~/stageM1% cd build
vhuber@wifi-irma13:~/stageM1/build% cmake ../src
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.9.1")
-- Configuring done
-- Generating done
-- Build files have been written to: ~/stageM1/build
vhuber@wifi-irma13:~/stageM1/build% make all
Scanning dependencies of target operationlib
[ 50%] Building CXX object CMakeFiles/operationlib.dir/operation.cpp.o
~/stageM1/src/operation.cpp:95:1: warning: control may reach end of
      non-void function [-Wreturn-type]
}
^
1 warning generated.
Linking CXX static library liboperationlib.a
[ 50%] Built target operationlib
Scanning dependencies of target operation
[100%] Building CXX object CMakeFiles/operation.dir/main.cpp.o
Linking CXX executable operation
[100%] Built target operation
vhuber@wifi-irma13:~/stageM1/build% ls -lah
total 156
drwxr-xr-x   9 vhuber  staff   306B 22 jui 10:25 .
drwxr-xr-x   7 vhuber  staff   238B 22 jui 10:25 ..
-rw-r--r--   1 vhuber  staff    13K 22 jui 10:25 CMakeCache.txt
drwxr-xr-x  18 vhuber  staff   612B 22 jui 10:25 CMakeFiles
-rw-r--r--   1 vhuber  staff   103K 22 jui 10:25 Doxyfile
-rw-r--r--   1 vhuber  staff   6,3K 22 jui 10:25 Makefile
-rw-r--r--   1 vhuber  staff   1,2K 22 jui 10:25 cmake_install.cmake
-rw-r--r--   1 vhuber  staff   2,9K 22 jui 10:25 liboperationlib.a
-rwxr-xr-x   1 vhuber  staff    20K 22 jui 10:25 operation
```

**Comment by aancel** [comment]
Add an option USE_SHARED:   
- If it is OFF: it will build a static library and link the executable with it  
- It if is ON : it will build a shared library and link with it  
  See http://www.cmake.org/cmake/help/v3.0/command/option.html  
  Please refer to the cmake documentation for all cmake related questions (like the configure( ... ) and add_custom_target( ... ) that I asked you to understand).
