### ISSUE TITLE
feelpp

### ISSUE THREAD

**Issue by wkyoshe** [wkyoshe/stageM1#19]
I still can't access the  feelpp installed on IRMA Atlas. I would like to test some examples in feel++.

**Comment by vhuber** [comment]
What do you mean ? Explain the problem.

**Comment by wkyoshe** [comment]
Like i said yesterday, i was not able to install feel++ on my laptop, then i thought maybe i could use it on my atlas account  but i failed.

**Comment by wkyoshe** [comment]
The thing is that i want to be able to compile and execute some feel++ examples on my computer  and i don't yet know how it's done. Do i have to install the feel++ application on my laptop?.
I read the [tutorial on feelpp-book](https://github.com/feelpp/feelpp-book/tree/master/GettingStarted) on how to download and compile but i did not understand it maybe. I tried installing and got stuck in the middle.

**Comment by vhuber** [comment]
**do not install Feel++ on your laptop**
You have to compile from source **and note whatever is not clear on the tutorial** to - later - add it to the tuto.

**Comment by wkyoshe** [comment]
It's the word  **compile from source** that i don't understand here.
