### ISSUE TITLE
Question1

### ISSUE THREAD

**Issue by wkyoshe** [wkyoshe/stageM1#2]
So far i haven't been able to compile and execute any feel++ example, i have tried hard to do it on my own and failed.
Also what is the extension for feel++ files
@vhuber @aancel

**Comment by vhuber** [comment]
You will find documentation about it on the following links
- [ ] Download (git) http://book.feelpp.org/content/GettingStarted/download.html
- [ ] Configure http://book.feelpp.org/content/GettingStarted/compiling.html

**DO NOT FORGET TO LOAD THE MODULE gcc49.profile on atlas**
See
https://github.com/feelpp/feelpp/wiki/Irma-Atlas-Cluster#modules

**Comment by wkyoshe** [comment]
Thanks

**Comment by wkyoshe** [comment]
Sorry, can i pass by your office so that you can help me step by step on doing this, i still can't solve my problem,
Thanks.

**Comment by vhuber** [comment]
Sure.

For that kind of question, please use gitter.
