### ISSUE TITLE
sub-repository

### ISSUE THREAD

**Issue by wkyoshe** [wkyoshe/stageM1#4]
How can i divide my main repository into two; one for reports and the other for source codes?

**Comment by vhuber** [comment]
With Linux, **everything** is a file (from the printer to the keyboard) with a particular type.
A directory is a file.
Just use it as a file.

``` bash
mkdir src
mkdir reports
git add src reports
git commit -m "splitting repo"
git push
```

**Comment by vhuber** [comment]
Why have you created two branches ?
that is not necessary.

**Comment by wkyoshe** [comment]
i was just trying to see what happens if i do that.

**Comment by wkyoshe** [comment]
so i should only leave the master branch?

**Comment by vhuber** [comment]
It'll be better yes.

branche are a tool to allow - for example - various version of same project, or developing a new feature without impacting the reste of the project during the development of that feature.

**Comment by wkyoshe** [comment]
so back to the source code, what was i real supposed to do?

**Comment by vhuber** [comment]
- create a directory named "src" containing your source code
- create a directory named "reports" containing each report.

**Comment by wkyoshe** [comment]
well i followed the  commands you sent me, but it still didn't work.
I still dont have two different directories, but i am still working on it.

**Comment by wkyoshe** [comment]
![screen shot 2015-06-15 at 20 19 49](https://cloud.githubusercontent.com/assets/12754740/8167039/f1e63854-139b-11e5-994b-657d9c8ba5f9.png)

**Comment by vhuber** [comment]
Good reflex: give the error code.
Better reflex: read it ;-) `You may want to first integrate the remote changes`

**Comment by vhuber** [comment]
Close the issue if you consider the question answered.
