### ISSUE TITLE
Merge makefiles

### ISSUE THREAD

**Issue by vhuber** [wkyoshe/stageM1#8]
HI,

There is no reason to have two makefiles. You can in a single one specify a lot of target.
Moreover, it is not possible to use the file named `Makefile2` : it has to be named `Makefile`.

**Comment by wkyoshe** [comment]
Hi, 
I have merged the two files. 
But i have a problem with my main.cpp.

**Comment by vhuber** [comment]
The Makefile is now correct.
Your class design is wrong.
Please have a look to [that](https://fr.wikibooks.org/wiki/Programmation_C%2B%2B/Les_classes#Exemples_de_classes)

**Comment by wkyoshe** [comment]
OK! let me do it
